# Generated by Django 3.0.7 on 2020-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20200812_1225"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
