# Generated by Django 3.0.7 on 2020-08-12 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20200812_1331"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="birthday",
            new_name="dob",
        ),
    ]
