# Generated by Django 3.1 on 2020-08-25 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_auto_20200812_1548"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dob",
        ),
    ]
