# Generated by Django 3.0.7 on 2020-07-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalinfo",
            name="item",
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="item",
            field=models.ManyToManyField(related_name="addinfo", to="items.Item"),
        ),
    ]
