# Generated by Django 3.0.7 on 2020-07-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_auto_20200727_2127"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalinfo",
            name="item",
        ),
        migrations.AddField(
            model_name="item",
            name="addinfo",
            field=models.ManyToManyField(
                related_name="addinfo", to="items.AdditionalInfo"
            ),
        ),
    ]
