# Generated by Django 3.0.7 on 2020-07-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_auto_20200727_2129"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
