# Generated by Django 3.0.7 on 2020-07-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="item",
            field=models.ForeignKey(
                default="100",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="items.Item",
            ),
        ),
    ]
