# Generated by Django 3.0.7 on 2020-07-27 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_auto_20200727_2135"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
    ]
