# Generated by Django 3.0.7 on 2020-07-28 09:18

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0007_auto_20200728_1443"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="review",
            name="rate",
            field=models.FloatField(null=True, validators=[items.models.validateRate]),
        ),
    ]
