# Generated by Django 3.0.7 on 2020-07-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0008_auto_20200728_1503"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Enter a Review"
            ),
        ),
    ]
