# Generated by Django 3.0.7 on 2020-07-28 17:11

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0009_auto_20200728_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.FloatField(
                default=0, null=True, validators=[items.models.validateRate]
            ),
        ),
    ]
