# Generated by Django 3.0.7 on 2020-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0010_auto_20200728_2256"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-datetime"]},
        ),
        migrations.AddField(
            model_name="review",
            name="datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
