# Generated by Django 3.0.7 on 2020-07-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0012_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
