# Generated by Django 3.0.7 on 2020-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0013_auto_20200729_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
