# Generated by Django 3.0.7 on 2020-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0014_cartitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
