# Generated by Django 3.0.7 on 2020-07-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0015_auto_20200729_1440"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
