# Generated by Django 3.0.7 on 2020-07-31 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0017_auto_20200729_1507"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.SubCategory",
            ),
        ),
    ]
