# Generated by Django 3.0.7 on 2020-07-31 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0018_auto_20200731_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                blank="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.Category",
            ),
        ),
    ]
