# Generated by Django 3.0.7 on 2020-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0021_auto_20200731_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
