# Generated by Django 3.0.7 on 2020-08-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0022_auto_20200731_1642"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collections",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                (
                    "photo",
                    models.ImageField(
                        upload_to="collections/dp", verbose_name="Display Picture"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="additionalinfo",
            name="addtoform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="photo",
            field=models.ImageField(
                default="D:\\ecommerce\\ecommerce\\media\\category\\dp\x08ags_women.png",
                upload_to="category/dp",
                verbose_name="Display Picture",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="additionalinfo",
            name="value",
            field=models.CharField(
                max_length=30,
                verbose_name="If values are plural, Plesae seperate by comma ','",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.Collections",
            ),
        ),
    ]
