# Generated by Django 3.0.7 on 2020-08-01 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0023_auto_20200801_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.Collections",
            ),
        ),
        migrations.AlterField(
            model_name="collections",
            name="photo",
            field=models.ImageField(
                max_length=200,
                upload_to="collections/dp",
                verbose_name="Display Picture",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(max_length=200, upload_to="items/pp"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.Category",
            ),
        ),
    ]
