# Generated by Django 3.0.7 on 2020-08-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0024_auto_20200801_1316"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="code",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
