# Generated by Django 3.0.7 on 2020-08-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0027_item_realtimeprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="realtimeprice",
            field=models.IntegerField(
                blank=True,
                default=0,
                verbose_name="Please donot edit this django will handle this on it's own",
            ),
        ),
    ]
