# Generated by Django 3.0.7 on 2020-08-10 22:20

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0028_auto_20200810_2217"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="discount",
            field=models.FloatField(
                default=0,
                validators=[items.models.validated_discount],
                verbose_name="Write did count percentage as decimal points like 0.1 for 10%, 0.35 for 35%, etc",
            ),
        ),
    ]
