# Generated by Django 3.0.7 on 2020-08-11 14:21

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0029_auto_20200810_2220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.IntegerField(
                default=0, null=True, validators=[items.models.validateRate]
            ),
        ),
    ]
