# Generated by Django 3.0.7 on 2020-08-11 14:24

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0030_auto_20200811_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.FloatField(
                default=0, null=True, validators=[items.models.validateRate]
            ),
        ),
    ]
