# Generated by Django 3.0.7 on 2020-08-11 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0031_auto_20200811_1424"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReply",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Enter a Reply",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now=True)),
                (
                    "review",
                    models.ForeignKey(
                        default="100",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="items.Review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
