# Generated by Django 3.1 on 2020-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0034_auto_20200817_2136"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideimaages",
            name="link",
            field=models.URLField(
                max_length=1000, null=True, verbose_name="redirects to"
            ),
        ),
        migrations.AlterField(
            model_name="slideimaages",
            name="photo",
            field=models.ImageField(
                upload_to="slide/pic", verbose_name="put a slide image"
            ),
        ),
    ]
