# Generated by Django 3.1 on 2020-08-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0035_auto_20200826_1419"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideimaages",
            name="link",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="redirects to"
            ),
        ),
    ]
