# Generated by Django 3.1 on 2020-08-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0036_auto_20200826_1747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tag",
            field=models.ManyToManyField(related_name="items", to="items.Tag"),
        ),
    ]
