# Generated by Django 3.1 on 2020-11-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0037_auto_20200828_1920"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="collection",
        ),
        migrations.AddField(
            model_name="item",
            name="subcategory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.category",
            ),
        ),
        migrations.DeleteModel(
            name="Collections",
        ),
    ]
