# Generated by Django 4.2.4 on 2023-08-31 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0038_auto_20201106_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="addinfo",
            field=models.ManyToManyField(
                blank=True, related_name="addinfo", to="items.additionalinfo"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.category",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="items.subcategory",
            ),
        ),
    ]
