# Generated by Django 4.2.4 on 2023-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0040_remove_item_subcategory"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SLideImaages",
            new_name="SlideImages",
        ),
        migrations.RemoveField(
            model_name="review",
            name="item",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.RemoveField(
            model_name="reviewreply",
            name="review",
        ),
        migrations.RemoveField(
            model_name="reviewreply",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
        migrations.AlterField(
            model_name="item",
            name="dateadded",
            field=models.DateField(auto_now=True, db_column="dateadded"),
        ),
        migrations.RenameField(
            model_name="item",
            old_name="dateadded",
            new_name="date_added",
        ),
        migrations.AlterField(
            model_name="item",
            name="desp",
            field=models.TextField(db_column="desp"),
        ),
        migrations.RenameField(
            model_name="item",
            old_name="desp",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="item",
            name="addinfo",
        ),
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.RemoveField(
            model_name="item",
            name="realtimeprice",
        ),
        migrations.RemoveField(
            model_name="item",
            name="tag",
        ),
        migrations.AddField(
            model_name="item",
            name="real_time_price",
            field=models.IntegerField(
                blank=True,
                db_column="realtimeprice",
                default=0,
                verbose_name="Please don't edit this django will handle this on it's own",
            ),
        ),
        migrations.DeleteModel(
            name="AdditionalInfo",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="ReviewReply",
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
