# Generated by Django 4.2.4 on 2023-09-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0041_rename_slideimaages_slideimages_remove_review_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='real_time_price',
        ),
        migrations.AddField(
            model_name='item',
            name='realtimeprice',
            field=models.IntegerField(null=True),
        ),
    ]
