# Generated by Django 4.2.4 on 2023-09-06 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0042_remove_item_real_time_price_item_realtimeprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="realtimeprice",
        ),
    ]
