# Generated by Django 4.2.4 on 2023-09-06 15:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0044_alter_item_description_websitesection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitesection",
            name="section_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
