# Generated by Django 4.2.4 on 2023-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0045_alter_websitesection_section_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitesection",
            name="section_title",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
