# Generated by Django 3.0.7 on 2020-07-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupoun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5)),
                ("fromdate", models.DateField(verbose_name="Starting date of offer")),
                ("todate", models.DateField(verbose_name="Ending date of offer")),
                (
                    "discount",
                    models.FloatField(
                        verbose_name="dicoount % 0.00 to 1 is equivalent to 0% to 100% respectively"
                    ),
                ),
            ],
        ),
    ]
