# Generated by Django 3.0.7 on 2020-07-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_coupoun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupoun",
            name="code",
            field=models.CharField(max_length=20),
        ),
    ]
