# Generated by Django 3.0.7 on 2020-08-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_auto_20200730_1443"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoneDeal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_bill",
                    models.FileField(
                        upload_to="deals/pdf", verbose_name="Please DOnot Edit the file"
                    ),
                ),
                (
                    "delievered",
                    models.BooleanField(
                        default=False, verbose_name="If the product is delievered"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="totalprice",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
