# Generated by Django 3.0.7 on 2020-08-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_auto_20200801_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="detail",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
