# Generated by Django 3.0.7 on 2020-08-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_delete_donedeal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="totalprice",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
