# Generated by Django 3.0.7 on 2020-08-08 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_cartitem_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
    ]
