# Generated by Django 3.0.7 on 2020-08-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0012_cartitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="belongs_to_order",
            field=models.BooleanField(default=False),
        ),
    ]
