# Generated by Django 3.0.7 on 2020-08-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0024_auto_20200801_1316"),
        ("cart", "0013_cartitem_belongs_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.Item"
            ),
        ),
    ]
