# Generated by Django 4.2.4 on 2023-09-06 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0015_auto_20200809_1342"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupoun",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="detail",
        ),
    ]
