# Generated by Django 3.0.7 on 2020-08-12 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0015_auto_20200809_1342"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("on the way", "on the way"),
                            ("delieverd", "delievered"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("cdate", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=40)),
                ("phone_no", models.CharField(max_length=40)),
                (
                    "discountamount",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("urlcode", models.SlugField(blank=True, max_length=100, null=True)),
                ("initialprice", models.IntegerField(blank=True, default=0, null=True)),
                ("totalprice", models.IntegerField(blank=True, default=0, null=True)),
                ("items", models.ManyToManyField(to="cart.CartItem")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckoutProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=40, null=True)),
                ("email", models.EmailField(max_length=60, null=True)),
                (
                    "phone_no",
                    models.CharField(max_length=20, verbose_name="Your Phone number"),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("cdate", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-cdate"],
            },
        ),
    ]
