# Generated by Django 3.0.7 on 2020-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Orders_for_checkout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
