# Generated by Django 3.0.7 on 2020-08-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Orders_for_checkout", "0002_order_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="uuidcode",
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
