# Generated by Django 3.1 on 2020-08-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Orders_for_checkout", "0003_order_uuidcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("on the way", "on the way"),
                    ("delievered", "delievered"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
