# Generated by Django 3.1 on 2020-08-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Orders_for_checkout", "0004_auto_20200824_1419"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="log",
            field=models.JSONField(blank=True, null=True, verbose_name="json log"),
        ),
    ]
