# Generated by Django 3.1 on 2020-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Orders_for_checkout", "0005_order_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cdate",
            field=models.DateField(auto_now=True),
        ),
    ]
