# Generated by Django 4.2.4 on 2023-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Orders_for_checkout", "0007_remove_order_log"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkoutprofile",
            options={"ordering": ["-created_date"]},
        ),
        migrations.RenameField(
            model_name="checkoutprofile",
            old_name="cdate",
            new_name="created_date",
        ),
        migrations.AlterField(
            model_name="order",
            name="cdate",
            field=models.DateField(auto_now=True, db_column="cdate"),
        ),
        migrations.RenameField(
            model_name="order",
            old_name="cdate",
            new_name="created_date",
        ),
        migrations.AlterField(
            model_name="order",
            name="discountamount",
            field=models.IntegerField(
                blank=True, db_column="discountamount", default=0, null=True
            ),
        ),
        migrations.RenameField(
            model_name="order",
            old_name="discountamount",
            new_name="discount_amount",
        ),
        migrations.AlterField(
            model_name="order",
            name="initialprice",
            field=models.IntegerField(
                blank=True, db_column="initialprice", default=0, null=True
            ),
        ),
        migrations.RenameField(
            model_name="order",
            old_name="initialprice",
            new_name="initial_price",
        ),
        migrations.AlterField(
            model_name="order",
            name="totalprice",
            field=models.IntegerField(
                blank=True, db_column="totalprice", default=0, null=True
            ),
        ),
        migrations.RenameField(
            model_name="order",
            old_name="totalprice",
            new_name="total_price",
        ),
        migrations.AlterField(
            model_name="order",
            name="urlcode",
            field=models.SlugField(
                blank=True, db_column="urlcode", max_length=100, null=True
            ),
        ),
        migrations.RenameField(
            model_name="order",
            old_name="urlcode",
            new_name="url_code",
        ),
        migrations.AlterField(
            model_name="order",
            name="uuidcode",
            field=models.CharField(
                blank=True, db_column="uuidcode", max_length=22, null=True
            ),
        ),
        migrations.RenameField(
            model_name="order",
            old_name="uuidcode",
            new_name="uuid_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
